name: game_of_life
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
